[project]
name = "realtimestt-browser"
version = "0.1.0"
description = "Realtimestt with browser captions for obs studio"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "nvidia-cublas-cu12>=12.9.2.10",
    "nvidia-cudnn-cu12==9.*",
    "realtimestt[faster-whisper]>=1.1.1",
]

[project.scripts]
whisperai = "whisperai:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false